package Manager;

public enum EventType {
    ADD_ALARM,
    ADD_ALARM_SIGNAL,
    DELETE_ALARM,
    DELETE_ALARM_SIGNAL,
    ALARM_TRIGGER,
    SET_WATCH,
    START_WATCH,
    STOP_WATCH,
    PAUSE_WATCH,
    CONTINUE_WATCH,
    UPDATE_WATCH,
    CLIENT_CONNECT,
    CLIENT_DISCONNECT,
    ADD_MESSAGE,
    START_WATCH_CLIENT,
    STOP_WATCH_CLIENT,
    PAUSE_WATCH_CLIENT,
    CONTINUE_WATCH_CLIENT
}
